name: Build and Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_URI }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ECR_URI }}:latest

    - name: Deploy CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: chatbot-service
        template: cloudformation/ecs-service.yaml
        capabilities: CAPABILITY_NAMED_IAM
        parameter-overrides: |
          VPCId=${{ secrets.VPC_ID }},
          PublicSubnet1Id=${{ secrets.SUBNET_1 }},
          PublicSubnet2Id=${{ secrets.SUBNET_2 }},
          ECRImage=${{ secrets.ECR_URI }}:latest
